services:
  web:
    container_name: lognow-web
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: lognow-php
    build: .
    environment:
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    container_name: lognow-db
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: lognow
    ports:
      - "3306:3306"
    volumes:
      - db_datos:/var/lib/mysql

  phpmyadmin:
    container_name: lognow-pma
    image: phpmyadmin:latest
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_datos:
