server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php;
    client_max_body_size 6M;

    # archivos estaticos (css, js, imagenes)
    location / {
        try_files $uri $uri/ =404;
    }

    # archivos php: busca primero en la raiz, si no en pages/
    location ~ \.php$ {
        try_files $uri /pages$uri =404;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
